# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

centerCPP <- function(x) {
    .Call(`_CONFINED_centerCPP`, x)
}

getUV <- function(x, eigspc) {
    .Call(`_CONFINED_getUV`, x, eigspc)
}

doRCCA <- function(x, y) {
    .Call(`_CONFINED_doRCCA`, x, y)
}

getQCPP <- function(x) {
    .Call(`_CONFINED_getQCPP`, x)
}

svdCPP <- function(x) {
    .Call(`_CONFINED_svdCPP`, x)
}

